### ISSUE TITLE
Usage with Nextjs

### ISSUE THREAD

**Issue by Anan7Codes** [MetinArslanturk/react-animation-on-scroll#1]
Do you have any examples of this package being used with Nextjs? I'm coming across a window is not defined error.

**Comment by kastamas** [comment]
Same

**Comment by MetinArslanturk** [comment]
Hey guys, thanks for your feedback. Actually I solved that bug but it seems I failed while releasing that version to NPM.
However to making it in guarantee, I made a clean new publish to npm as a version 5.0.0.
So just update your package.json version like:
`"react-animation-on-scroll": "^5.0.0"`

Tested it with latest version NextJS and it seems it works. I am closing this issue now, if you guys catch any other thing, please don't hesitate about to opening a new issue.
