### ISSUE TITLE
Put an anchor option 

### ISSUE THREAD

**Issue by Sulley93** [MetinArslanturk/react-animation-on-scroll#12]
I think that it will be nice to have an anchor option, accepting css  selector (e.g. #myApp), that will animati when the anchor element reach the offset. This will allow to do "group animations" in sequence

**Comment by MetinArslanturk** [comment]
I think this is a bad pattern for a React library. In generel, it is better to prevent direct access of a DOM node (via selectors i.e). in React. This can break React's internal. We are generally accessing nodes through refs,  you can check it in here: https://beta.reactjs.org/learn/manipulating-the-dom-with-refs
