### ISSUE TITLE
Prevent animation on initially visible elements

### ISSUE THREAD

**Issue by garrytaulu** [MetinArslanturk/react-animation-on-scroll#15]
Is it possible to prevent the animation if the elements will be visible without scrolling? (i.e. "above the fold")

**Comment by MetinArslanturk** [comment]
Hmm... This can be handled by the code-side. If you believe it will be on the screen initially/constantly just don't use library for that element basically :) Otherwise, if it has dynamic situattion (sometimes on the screen at initial and sometimes not) then again at the code side you can detect it and  wrap / don't wrap element conditionally.

Finally, of course we can provide this as a feature. Added it to personal roadmap. Thanks for advise.

**Comment by garrytaulu** [comment]
> Hmm... This can be handled by the code-side. If you believe it will be on the screen initially/constantly just don't use library for that element basically :) Otherwise, if it has dynamic situattion (sometimes on the screen at initial and sometimes not) then again at the code side you can detect it and  wrap / don't wrap element conditionally.
> 
> 
> 
> Finally, of course we can provide this as a feature. Added it to personal roadmap. Thanks for advise.

Thank you for the reply 😊 

Another question which is kind of related (I can create a new issue if required), is there a way to remove all event listeners that you add? I have a button that removes the animation wrapper from my elements on a page but because I am setting a different parent element it seems to be still attempting to get the clientHeight on the elements that previously were wrapped because I can still see the scroll listener is attached. 

I'm not at my computer at the moment but can provide more info later. 

There doesn't seem to be a way to do this myself https://stackoverflow.com/questions/68938727/remove-event-listener-without-knowing-what-the-call-back-function-is

**Comment by MetinArslanturk** [comment]
Okay we may have a simple solution for this. We may have a new prop "listenerRef" it takes a ref (useRef) and sets it's .current to listener function. So, when you want to remove listener you can simply call something like removeListener("scroll", myRef.current).I will implement this when I find an empty time or open for contributions of course :)
