### ISSUE TITLE
Horizontal page

### ISSUE THREAD

**Issue by alekoisaev** [MetinArslanturk/react-animation-on-scroll#2]
I have horizontal scrolling page. width 100% and height 100vh. Animation work once on page first loading. and div which is not in viewport also load before I scroll to them.

How to fix it?

**Comment by MetinArslanturk** [comment]
Hey, thanks for question.

Unfortunately, this library supports only **Vertical** scrolling. If you check the source code it only calculates based on clientTop, offsetTop etc (y direction) values. We can duplicate component and change all vertical based values with horizontal based ones. So we can provide an alternative library for horizontal scrolling.

At the moment, I am a bit busy for this task. But I am open for merge requests. Please feel free to contributing. Now I am closing this issue with tagging as enhancement.

Thanks again,
Metin
