### ISSUE TITLE
Animation after content update?

### ISSUE THREAD

**Issue by itsdwizzy** [MetinArslanturk/react-animation-on-scroll#3]
First of all thank you for creating a awesome library.

I'm trying to animate text which is delivered through a API. Usually this has a small delay. 
In the example below, the content is displayed instantly however I would like to animate it as soon as the content is ready.

```
import React from 'react';
import { AnimationOnScroll as AOS } from 'react-animation-on-scroll';

export default class App extends React.Component {
    constructor (props: any) {
        super(props);

        this.state = {
            content: ""
        }
    }

    componentDidMount () {
        setTimeout (() => {
            this.setState({ content: "Hello world!" });
        }, 5000);
    }

    render () {
        const { content } = this.state;

        return (
            <AOS animateIn="animate__fadeInDown" duration={1} initiallyVisible>
                <h1>{content}</h1>
            </AOS>
        );
    }
}
```

I tried using the flag `initiallyVisible` as you suggest this should be set with server side rendering. However the results were the same.

Changing the timeout from `5000` to `0` shows the animation properly.

Is there any way to achieve this?

**Comment by MetinArslanturk** [comment]
Hi, you can implement a custom component with a conditional pattern. I mean that, a component like this:

```
const ConditionalRender = ({isDataLoaded, contentWhenLoaded, contentWhenNOTLoaded}) => {

 if (isDataLoaded) {
   return contentWhenLoaded;
 } else {
  return contentWhenNOTLoaded;
 }
}
```

Now you can use this special component in your app in similar situations:

```
<ConditionalRender
  isDataLoaded={!!this.state.content}
  contentWhenNOTLoaded={<div>Loading...</div>}
  contentWhenLoaded={<AOS animateIn="animate__fadeInDown" initiallyVisible>
                <h1>{this.state.content}</h1>
            </AOS>}
/>
```

This code just an example of approach. I didn't try it directly so you should implement it yourself. But you got the point, I mean that "don't" render the AnimationOnScroll wrapper until data is really loaded.

**Comment by itsdwizzy** [comment]
I understand your approach. Didn't think of it that way, but will work out just fine for me.

Thank you for your support @MetinArslanturk.
