### ISSUE TITLE
"animate__fadeInRightBig" makes the mobile screen too wide

### ISSUE THREAD

**Issue by ctnkaan** [MetinArslanturk/react-animation-on-scroll#4]
"animate__fadeInRightBig" seems to make the website too big when triggered on on mobile view. I don't know if it's a problem on my end but other animations work fine.

![image](https://user-images.githubusercontent.com/59853931/158701180-b4f051f6-7496-4755-aeeb-a4f77d43d7a0.png)

**Comment by MetinArslanturk** [comment]
Hi, firstly thanks for your feedback.

I need to point out that, this animation library works based on "animate.css" library. Which it provides pre-defined animation classes on CSS. This library in a general look, checks scroll position on a page and adds css classes which provided by animate.css library.

So, when an animation breaks a page layout or has another problem it is mostly about animate.css classes.

You can try the animations in here : https://animate.style/

And the source code of fadeInRightBig is here: https://github.com/animate-css/animate.css/blob/main/source/fading_entrances/fadeInRightBig.css

It starts animation with `transform: translate3d(2000px, 0, 0);`
This 2000px translate probably breaking your test browser.

Please try it on different browsers for PC and mobile phone. You can open an issue to animate.css library or even you can open an issue to problematic browser with your detections :)

If you got some detections which show this library has buggy points, then feel free to share please.

**Comment by ctnkaan** [comment]
Alright thank you. Love this animation library. I'll close this issue since the problem does not seem to come from this library. Thanks for your feedback!
