### ISSUE TITLE
Unregistered dependency on prop-types

### ISSUE THREAD

**Issue by AndrewCEmil** [MetinArslanturk/react-animation-on-scroll#5]
It looks like this package requires prop-types, but doesn't define it in the package.json file. This causes errors if you try to install it into a project that doesn't already have prop-types.

You can see the import here: https://github.com/MetinArslanturk/react-animation-on-scroll/blob/main/dist/esm/components/AnimationOnScroll.js#L1.

**Comment by AndrewCEmil** [comment]
https://github.com/MetinArslanturk/react-animation-on-scroll/pull/6 opened PR to address this issue.

**Comment by MetinArslanturk** [comment]
Hey @AndrewCEmil thanks for your catch and pull request. Good one. It seems I missed it while copying some babel configs from another project.
It comes from: https://github.com/MetinArslanturk/react-animation-on-scroll/blob/50aac5c0fa17c9d902f30b05e058e8662a7c6b4d/.babelrc#L6

But I think we should get rid of from prop-types. This project is completely written in TypeScript and prop-types main purpose is a "type checking if you don't have typescript in development mode" ([source](https://reactjs.org/docs/typechecking-with-proptypes.html)). So, while we have TypeScript here, we don't need prop-types. I will remove it completely.

I will publish .d.ts files with the project files. So, it will be type-safe for typescript projects.

**Comment by MetinArslanturk** [comment]
By the way, a fun fact, I think React already has prop-types dependency internally. So, you always having it even you don't have it in your package.json

But React core member says don't trust this and include it in your package.json ([source](https://github.com/facebook/create-react-app/issues/3985#issuecomment-363410237))

**Comment by MetinArslanturk** [comment]
Now I released a new version (5.1.0) and removed prop-types completely. Again, thanks for catch!
