### ISSUE TITLE
Doesn't work in Next.js

### ISSUE THREAD

**Issue by nisalk96** [MetinArslanturk/react-animation-on-scroll#9]
I installed the anime.css package and imported the CSS package to the file but it doesn't work, it stays hidden and does not reveal.
Next.js
![image](https://user-images.githubusercontent.com/26079832/184989234-004897ef-4b56-41e9-a368-138ecc099492.png)

**Comment by MetinArslanturk** [comment]
Where and how did you import animate.css file? Can you share a full project example?

**Comment by nisalk96** [comment]
I used Next.js an imported animate.css in to _app.jsx file , I'm sorry but this project is client project and it's deployed

**Comment by MetinArslanturk** [comment]
Can you create a dummy nextjs project with same conditions and test it? If it does not work then you can share the source code and I can check it.

**Comment by ignacio-dev** [comment]
I am having the same issue. The animation loads fine if the component is in view on page load, but if not, it never triggers

**Comment by MetinArslanturk** [comment]
I will deploy an example with NextJS soon, it will be added to README.
